#!/usr/bin/env node
/**
 * Bundle the catalog, palette and generator into the behaviour pack.
 *
 * The alternative was shipping 68 `.mcstructure` files. Willis Tower alone is
 * ~14 MB of block indices, and Bedrock structure blocks cap at 64x384x64 so the
 * big ones cannot be placed that way at all.
 *
 * Instead the pack ships the *description* — the catalog and the palette, about
 * 100 KB — plus the generator itself, and builds geometry in-game. Same code
 * path as the build-time tools, so a building looks identical either way.
 *
 *   node tools/build-runtime.mjs
 */

import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { loadCatalog, validateCatalog } from './lib/catalog.mjs'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const SCRIPTS = join(ROOT, 'packs', 'city_builder_bp', 'scripts')
const LIB = join(SCRIPTS, 'lib')

const catalog = loadCatalog()
const errors = validateCatalog(catalog)
if (errors.length) {
    console.error(`catalog is invalid; refusing to bundle:\n  - ${errors.join('\n  - ')}`)
    process.exit(1)
}

mkdirSync(LIB, { recursive: true })

// --- data ------------------------------------------------------------------

const materials = JSON.parse(readFileSync(join(ROOT, 'data', 'palettes', 'materials.json'), 'utf8')).systems
const rotationTable = JSON.parse(readFileSync(join(ROOT, 'data', 'block-states', 'rotation.json'), 'utf8'))
const streets = JSON.parse(readFileSync(join(ROOT, 'data', 'streets', 'chicago.json'), 'utf8'))
const districts = JSON.parse(readFileSync(join(ROOT, 'data', 'districts', 'chicago.json'), 'utf8')).tiles
const transit = JSON.parse(readFileSync(join(ROOT, 'data', 'transit', 'chicago.json'), 'utf8'))
const cities = JSON.parse(readFileSync(join(ROOT, 'data', 'cities', 'chicago.json'), 'utf8')).cities

/** Only the fields the runtime generator actually reads. */
function slim(entry) {
    return {
        id: entry.id,
        name: entry.name,
        type: entry.type,
        tier: entry.tier,
        // Needed at runtime: the roofing kit is chosen from the era, and the
        // placement dialog shows the inspiration.
        provenance: entry.provenance,
        massing: entry.massing,
        below_grade: entry.below_grade,
        structure: entry.structure,
        vertical: entry.vertical,
        facade: entry.facade,
        program: entry.program
    }
}

const data =
    `// GENERATED by tools/build-runtime.mjs — do not edit.\n` +
    `// ${catalog.length} building presets and ${Object.keys(materials).length} material bindings.\n` +
    `export const CATALOG = ${JSON.stringify(catalog.map(slim))}\n\n` +
    `export const MATERIAL_SYSTEMS = ${JSON.stringify(materials)}\n\n` +
    `export const ROTATION_TABLE = ${JSON.stringify(rotationTable)}\n\n` +
    `export const STREETS = ${JSON.stringify(streets)}\n\n` +
    `export const DISTRICTS = ${JSON.stringify(districts)}\n\n` +
    `export const TRANSIT = ${JSON.stringify(transit)}\n\n` +
    `export const CITIES = ${JSON.stringify(cities)}\n`

writeFileSync(join(LIB, 'catalog_data.js'), data)

// --- generator -------------------------------------------------------------
//
// generate.mjs and interior.mjs are deliberately free of Node imports, so they
// are copied verbatim rather than transpiled. If either ever grows a `node:`
// import this build fails loudly instead of shipping a pack that will not load.

for (const name of ['generate.mjs', 'interior.mjs', 'rotation.mjs', 'fitout.mjs', 'street.mjs', 'transit.mjs', 'district.mjs', 'city.mjs']) {
    const source = readFileSync(join(ROOT, 'tools', 'lib', name), 'utf8')
    if (/from ['"]node:/.test(source)) {
        console.error(`lib/${name} imports a node: module and cannot run inside Bedrock.`)
        process.exit(1)
    }
    writeFileSync(join(LIB, name.replace('.mjs', '.js')), source.replace(/from '(\.\/[\w-]+)\.mjs'/g, "from '$1.js'"))
}

const bytes = (path) => readFileSync(path).length
console.log(`bundled ${catalog.length} presets, ${Object.keys(materials).length} material systems`)
console.log(`  scripts/lib/catalog_data.js  ${(bytes(join(LIB, 'catalog_data.js')) / 1024).toFixed(0)} KB`)
console.log(`  scripts/lib/generate.js      ${(bytes(join(LIB, 'generate.js')) / 1024).toFixed(0)} KB`)
console.log(`  scripts/lib/interior.js      ${(bytes(join(LIB, 'interior.js')) / 1024).toFixed(0)} KB`)
console.log(`  scripts/lib/rotation.js      ${(bytes(join(LIB, 'rotation.js')) / 1024).toFixed(0)} KB`)
console.log(`  scripts/lib/fitout.js        ${(bytes(join(LIB, 'fitout.js')) / 1024).toFixed(0)} KB`)
