// GENERATED by tools/gen-rotation-probe.mjs — do not edit.
// Expected block states for each orientation of the M2 rotation probe.
export const PROBE_EXPECTATIONS = {
  "r0": {
    "footprint": [
      24,
      4,
      21
    ],
    "cells": [
      {
        "pos": [
          1,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 0
        },
        "label": "weirdo_direction=0"
      },
      {
        "pos": [
          4,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 1
        },
        "label": "weirdo_direction=1"
      },
      {
        "pos": [
          7,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 2
        },
        "label": "weirdo_direction=2"
      },
      {
        "pos": [
          10,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 3
        },
        "label": "weirdo_direction=3"
      },
      {
        "pos": [
          13,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 0
        },
        "label": "weirdo_direction=0 (upsidedown)"
      },
      {
        "pos": [
          16,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 2
        },
        "label": "weirdo_direction=2 (upsidedown)"
      },
      {
        "pos": [
          19,
          1,
          1
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=0"
      },
      {
        "pos": [
          22,
          1,
          1
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=1"
      },
      {
        "pos": [
          1,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=2"
      },
      {
        "pos": [
          4,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=3"
      },
      {
        "pos": [
          7,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=0 (open)"
      },
      {
        "pos": [
          10,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=1 (open)"
      },
      {
        "pos": [
          13,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=2 (open)"
      },
      {
        "pos": [
          16,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=3 (open)"
      },
      {
        "pos": [
          19,
          1,
          4
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 0
        },
        "label": "facing_direction=0"
      },
      {
        "pos": [
          22,
          1,
          4
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 1
        },
        "label": "facing_direction=1"
      },
      {
        "pos": [
          1,
          1,
          7
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 2
        },
        "label": "facing_direction=2"
      },
      {
        "pos": [
          4,
          1,
          7
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 3
        },
        "label": "facing_direction=3"
      },
      {
        "pos": [
          7,
          1,
          7
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 4
        },
        "label": "facing_direction=4"
      },
      {
        "pos": [
          10,
          1,
          7
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 5
        },
        "label": "facing_direction=5"
      },
      {
        "pos": [
          13,
          1,
          7
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 0
        },
        "label": "ground_sign_direction=0"
      },
      {
        "pos": [
          16,
          1,
          7
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 2
        },
        "label": "ground_sign_direction=2"
      },
      {
        "pos": [
          19,
          1,
          7
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 4
        },
        "label": "ground_sign_direction=4"
      },
      {
        "pos": [
          22,
          1,
          7
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 6
        },
        "label": "ground_sign_direction=6"
      },
      {
        "pos": [
          1,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 8
        },
        "label": "ground_sign_direction=8"
      },
      {
        "pos": [
          4,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 10
        },
        "label": "ground_sign_direction=10"
      },
      {
        "pos": [
          7,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 12
        },
        "label": "ground_sign_direction=12"
      },
      {
        "pos": [
          10,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 14
        },
        "label": "ground_sign_direction=14"
      },
      {
        "pos": [
          13,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "north"
        },
        "label": "minecraft:cardinal_direction=north"
      },
      {
        "pos": [
          16,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "south"
        },
        "label": "minecraft:cardinal_direction=south"
      },
      {
        "pos": [
          19,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "east"
        },
        "label": "minecraft:cardinal_direction=east"
      },
      {
        "pos": [
          22,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "west"
        },
        "label": "minecraft:cardinal_direction=west"
      },
      {
        "pos": [
          1,
          1,
          13
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "x"
        },
        "label": "pillar_axis=x"
      },
      {
        "pos": [
          4,
          1,
          13
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "y"
        },
        "label": "pillar_axis=y"
      },
      {
        "pos": [
          7,
          1,
          13
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "z"
        },
        "label": "pillar_axis=z"
      },
      {
        "pos": [
          10,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 0
        },
        "label": "rail_direction=0"
      },
      {
        "pos": [
          13,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 1
        },
        "label": "rail_direction=1"
      },
      {
        "pos": [
          16,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 2
        },
        "label": "rail_direction=2"
      },
      {
        "pos": [
          19,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 3
        },
        "label": "rail_direction=3"
      },
      {
        "pos": [
          22,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 4
        },
        "label": "rail_direction=4"
      },
      {
        "pos": [
          1,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 5
        },
        "label": "rail_direction=5"
      },
      {
        "pos": [
          4,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 6
        },
        "label": "rail_direction=6"
      },
      {
        "pos": [
          7,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 7
        },
        "label": "rail_direction=7"
      },
      {
        "pos": [
          10,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 8
        },
        "label": "rail_direction=8"
      },
      {
        "pos": [
          13,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 9
        },
        "label": "rail_direction=9"
      },
      {
        "pos": [
          16,
          1,
          16
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "up"
        },
        "label": "minecraft:block_face=up"
      },
      {
        "pos": [
          19,
          1,
          16
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "north"
        },
        "label": "minecraft:block_face=north"
      },
      {
        "pos": [
          22,
          1,
          16
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "south"
        },
        "label": "minecraft:block_face=south"
      },
      {
        "pos": [
          1,
          1,
          19
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "east"
        },
        "label": "minecraft:block_face=east"
      },
      {
        "pos": [
          4,
          1,
          19
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "west"
        },
        "label": "minecraft:block_face=west"
      }
    ]
  },
  "r90": {
    "footprint": [
      21,
      4,
      24
    ],
    "cells": [
      {
        "pos": [
          19,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 2
        },
        "label": "weirdo_direction=0"
      },
      {
        "pos": [
          19,
          1,
          4
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 3
        },
        "label": "weirdo_direction=1"
      },
      {
        "pos": [
          19,
          1,
          7
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 1
        },
        "label": "weirdo_direction=2"
      },
      {
        "pos": [
          19,
          1,
          10
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 0
        },
        "label": "weirdo_direction=3"
      },
      {
        "pos": [
          19,
          1,
          13
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 2
        },
        "label": "weirdo_direction=0 (upsidedown)"
      },
      {
        "pos": [
          19,
          1,
          16
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 1
        },
        "label": "weirdo_direction=2 (upsidedown)"
      },
      {
        "pos": [
          19,
          1,
          19
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=0"
      },
      {
        "pos": [
          19,
          1,
          22
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=1"
      },
      {
        "pos": [
          16,
          1,
          1
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=2"
      },
      {
        "pos": [
          16,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=3"
      },
      {
        "pos": [
          16,
          1,
          7
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=0 (open)"
      },
      {
        "pos": [
          16,
          1,
          10
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=1 (open)"
      },
      {
        "pos": [
          16,
          1,
          13
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=2 (open)"
      },
      {
        "pos": [
          16,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=3 (open)"
      },
      {
        "pos": [
          16,
          1,
          19
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 0
        },
        "label": "facing_direction=0"
      },
      {
        "pos": [
          16,
          1,
          22
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 1
        },
        "label": "facing_direction=1"
      },
      {
        "pos": [
          13,
          1,
          1
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 5
        },
        "label": "facing_direction=2"
      },
      {
        "pos": [
          13,
          1,
          4
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 4
        },
        "label": "facing_direction=3"
      },
      {
        "pos": [
          13,
          1,
          7
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 2
        },
        "label": "facing_direction=4"
      },
      {
        "pos": [
          13,
          1,
          10
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 3
        },
        "label": "facing_direction=5"
      },
      {
        "pos": [
          13,
          1,
          13
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 4
        },
        "label": "ground_sign_direction=0"
      },
      {
        "pos": [
          13,
          1,
          16
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 6
        },
        "label": "ground_sign_direction=2"
      },
      {
        "pos": [
          13,
          1,
          19
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 8
        },
        "label": "ground_sign_direction=4"
      },
      {
        "pos": [
          13,
          1,
          22
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 10
        },
        "label": "ground_sign_direction=6"
      },
      {
        "pos": [
          10,
          1,
          1
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 12
        },
        "label": "ground_sign_direction=8"
      },
      {
        "pos": [
          10,
          1,
          4
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 14
        },
        "label": "ground_sign_direction=10"
      },
      {
        "pos": [
          10,
          1,
          7
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 0
        },
        "label": "ground_sign_direction=12"
      },
      {
        "pos": [
          10,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 2
        },
        "label": "ground_sign_direction=14"
      },
      {
        "pos": [
          10,
          1,
          13
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "east"
        },
        "label": "minecraft:cardinal_direction=north"
      },
      {
        "pos": [
          10,
          1,
          16
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "west"
        },
        "label": "minecraft:cardinal_direction=south"
      },
      {
        "pos": [
          10,
          1,
          19
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "south"
        },
        "label": "minecraft:cardinal_direction=east"
      },
      {
        "pos": [
          10,
          1,
          22
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "north"
        },
        "label": "minecraft:cardinal_direction=west"
      },
      {
        "pos": [
          7,
          1,
          1
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "z"
        },
        "label": "pillar_axis=x"
      },
      {
        "pos": [
          7,
          1,
          4
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "y"
        },
        "label": "pillar_axis=y"
      },
      {
        "pos": [
          7,
          1,
          7
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "x"
        },
        "label": "pillar_axis=z"
      },
      {
        "pos": [
          7,
          1,
          10
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 1
        },
        "label": "rail_direction=0"
      },
      {
        "pos": [
          7,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 0
        },
        "label": "rail_direction=1"
      },
      {
        "pos": [
          7,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 5
        },
        "label": "rail_direction=2"
      },
      {
        "pos": [
          7,
          1,
          19
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 4
        },
        "label": "rail_direction=3"
      },
      {
        "pos": [
          7,
          1,
          22
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 2
        },
        "label": "rail_direction=4"
      },
      {
        "pos": [
          4,
          1,
          1
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 3
        },
        "label": "rail_direction=5"
      },
      {
        "pos": [
          4,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 7
        },
        "label": "rail_direction=6"
      },
      {
        "pos": [
          4,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 8
        },
        "label": "rail_direction=7"
      },
      {
        "pos": [
          4,
          1,
          10
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 9
        },
        "label": "rail_direction=8"
      },
      {
        "pos": [
          4,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 6
        },
        "label": "rail_direction=9"
      },
      {
        "pos": [
          4,
          1,
          16
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "up"
        },
        "label": "minecraft:block_face=up"
      },
      {
        "pos": [
          4,
          1,
          19
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "east"
        },
        "label": "minecraft:block_face=north"
      },
      {
        "pos": [
          4,
          1,
          22
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "west"
        },
        "label": "minecraft:block_face=south"
      },
      {
        "pos": [
          1,
          1,
          1
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "south"
        },
        "label": "minecraft:block_face=east"
      },
      {
        "pos": [
          1,
          1,
          4
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "north"
        },
        "label": "minecraft:block_face=west"
      }
    ]
  },
  "r180": {
    "footprint": [
      24,
      4,
      21
    ],
    "cells": [
      {
        "pos": [
          22,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 1
        },
        "label": "weirdo_direction=0"
      },
      {
        "pos": [
          19,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 0
        },
        "label": "weirdo_direction=1"
      },
      {
        "pos": [
          16,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 3
        },
        "label": "weirdo_direction=2"
      },
      {
        "pos": [
          13,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 2
        },
        "label": "weirdo_direction=3"
      },
      {
        "pos": [
          10,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 1
        },
        "label": "weirdo_direction=0 (upsidedown)"
      },
      {
        "pos": [
          7,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 3
        },
        "label": "weirdo_direction=2 (upsidedown)"
      },
      {
        "pos": [
          4,
          1,
          19
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=0"
      },
      {
        "pos": [
          1,
          1,
          19
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=1"
      },
      {
        "pos": [
          22,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=2"
      },
      {
        "pos": [
          19,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=3"
      },
      {
        "pos": [
          16,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=0 (open)"
      },
      {
        "pos": [
          13,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=1 (open)"
      },
      {
        "pos": [
          10,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=2 (open)"
      },
      {
        "pos": [
          7,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=3 (open)"
      },
      {
        "pos": [
          4,
          1,
          16
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 0
        },
        "label": "facing_direction=0"
      },
      {
        "pos": [
          1,
          1,
          16
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 1
        },
        "label": "facing_direction=1"
      },
      {
        "pos": [
          22,
          1,
          13
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 3
        },
        "label": "facing_direction=2"
      },
      {
        "pos": [
          19,
          1,
          13
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 2
        },
        "label": "facing_direction=3"
      },
      {
        "pos": [
          16,
          1,
          13
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 5
        },
        "label": "facing_direction=4"
      },
      {
        "pos": [
          13,
          1,
          13
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 4
        },
        "label": "facing_direction=5"
      },
      {
        "pos": [
          10,
          1,
          13
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 8
        },
        "label": "ground_sign_direction=0"
      },
      {
        "pos": [
          7,
          1,
          13
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 10
        },
        "label": "ground_sign_direction=2"
      },
      {
        "pos": [
          4,
          1,
          13
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 12
        },
        "label": "ground_sign_direction=4"
      },
      {
        "pos": [
          1,
          1,
          13
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 14
        },
        "label": "ground_sign_direction=6"
      },
      {
        "pos": [
          22,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 0
        },
        "label": "ground_sign_direction=8"
      },
      {
        "pos": [
          19,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 2
        },
        "label": "ground_sign_direction=10"
      },
      {
        "pos": [
          16,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 4
        },
        "label": "ground_sign_direction=12"
      },
      {
        "pos": [
          13,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 6
        },
        "label": "ground_sign_direction=14"
      },
      {
        "pos": [
          10,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "south"
        },
        "label": "minecraft:cardinal_direction=north"
      },
      {
        "pos": [
          7,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "north"
        },
        "label": "minecraft:cardinal_direction=south"
      },
      {
        "pos": [
          4,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "west"
        },
        "label": "minecraft:cardinal_direction=east"
      },
      {
        "pos": [
          1,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "east"
        },
        "label": "minecraft:cardinal_direction=west"
      },
      {
        "pos": [
          22,
          1,
          7
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "x"
        },
        "label": "pillar_axis=x"
      },
      {
        "pos": [
          19,
          1,
          7
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "y"
        },
        "label": "pillar_axis=y"
      },
      {
        "pos": [
          16,
          1,
          7
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "z"
        },
        "label": "pillar_axis=z"
      },
      {
        "pos": [
          13,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 0
        },
        "label": "rail_direction=0"
      },
      {
        "pos": [
          10,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 1
        },
        "label": "rail_direction=1"
      },
      {
        "pos": [
          7,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 3
        },
        "label": "rail_direction=2"
      },
      {
        "pos": [
          4,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 2
        },
        "label": "rail_direction=3"
      },
      {
        "pos": [
          1,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 5
        },
        "label": "rail_direction=4"
      },
      {
        "pos": [
          22,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 4
        },
        "label": "rail_direction=5"
      },
      {
        "pos": [
          19,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 8
        },
        "label": "rail_direction=6"
      },
      {
        "pos": [
          16,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 9
        },
        "label": "rail_direction=7"
      },
      {
        "pos": [
          13,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 6
        },
        "label": "rail_direction=8"
      },
      {
        "pos": [
          10,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 7
        },
        "label": "rail_direction=9"
      },
      {
        "pos": [
          7,
          1,
          4
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "up"
        },
        "label": "minecraft:block_face=up"
      },
      {
        "pos": [
          4,
          1,
          4
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "south"
        },
        "label": "minecraft:block_face=north"
      },
      {
        "pos": [
          1,
          1,
          4
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "north"
        },
        "label": "minecraft:block_face=south"
      },
      {
        "pos": [
          22,
          1,
          1
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "west"
        },
        "label": "minecraft:block_face=east"
      },
      {
        "pos": [
          19,
          1,
          1
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "east"
        },
        "label": "minecraft:block_face=west"
      }
    ]
  },
  "r270": {
    "footprint": [
      21,
      4,
      24
    ],
    "cells": [
      {
        "pos": [
          1,
          1,
          22
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 3
        },
        "label": "weirdo_direction=0"
      },
      {
        "pos": [
          1,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 2
        },
        "label": "weirdo_direction=1"
      },
      {
        "pos": [
          1,
          1,
          16
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 0
        },
        "label": "weirdo_direction=2"
      },
      {
        "pos": [
          1,
          1,
          13
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 1
        },
        "label": "weirdo_direction=3"
      },
      {
        "pos": [
          1,
          1,
          10
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 3
        },
        "label": "weirdo_direction=0 (upsidedown)"
      },
      {
        "pos": [
          1,
          1,
          7
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 0
        },
        "label": "weirdo_direction=2 (upsidedown)"
      },
      {
        "pos": [
          1,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=0"
      },
      {
        "pos": [
          1,
          1,
          1
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=1"
      },
      {
        "pos": [
          4,
          1,
          22
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=2"
      },
      {
        "pos": [
          4,
          1,
          19
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=3"
      },
      {
        "pos": [
          4,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=0 (open)"
      },
      {
        "pos": [
          4,
          1,
          13
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=1 (open)"
      },
      {
        "pos": [
          4,
          1,
          10
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=2 (open)"
      },
      {
        "pos": [
          4,
          1,
          7
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=3 (open)"
      },
      {
        "pos": [
          4,
          1,
          4
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 0
        },
        "label": "facing_direction=0"
      },
      {
        "pos": [
          4,
          1,
          1
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 1
        },
        "label": "facing_direction=1"
      },
      {
        "pos": [
          7,
          1,
          22
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 4
        },
        "label": "facing_direction=2"
      },
      {
        "pos": [
          7,
          1,
          19
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 5
        },
        "label": "facing_direction=3"
      },
      {
        "pos": [
          7,
          1,
          16
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 3
        },
        "label": "facing_direction=4"
      },
      {
        "pos": [
          7,
          1,
          13
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 2
        },
        "label": "facing_direction=5"
      },
      {
        "pos": [
          7,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 12
        },
        "label": "ground_sign_direction=0"
      },
      {
        "pos": [
          7,
          1,
          7
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 14
        },
        "label": "ground_sign_direction=2"
      },
      {
        "pos": [
          7,
          1,
          4
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 0
        },
        "label": "ground_sign_direction=4"
      },
      {
        "pos": [
          7,
          1,
          1
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 2
        },
        "label": "ground_sign_direction=6"
      },
      {
        "pos": [
          10,
          1,
          22
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 4
        },
        "label": "ground_sign_direction=8"
      },
      {
        "pos": [
          10,
          1,
          19
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 6
        },
        "label": "ground_sign_direction=10"
      },
      {
        "pos": [
          10,
          1,
          16
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 8
        },
        "label": "ground_sign_direction=12"
      },
      {
        "pos": [
          10,
          1,
          13
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 10
        },
        "label": "ground_sign_direction=14"
      },
      {
        "pos": [
          10,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "west"
        },
        "label": "minecraft:cardinal_direction=north"
      },
      {
        "pos": [
          10,
          1,
          7
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "east"
        },
        "label": "minecraft:cardinal_direction=south"
      },
      {
        "pos": [
          10,
          1,
          4
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "north"
        },
        "label": "minecraft:cardinal_direction=east"
      },
      {
        "pos": [
          10,
          1,
          1
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "south"
        },
        "label": "minecraft:cardinal_direction=west"
      },
      {
        "pos": [
          13,
          1,
          22
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "z"
        },
        "label": "pillar_axis=x"
      },
      {
        "pos": [
          13,
          1,
          19
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "y"
        },
        "label": "pillar_axis=y"
      },
      {
        "pos": [
          13,
          1,
          16
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "x"
        },
        "label": "pillar_axis=z"
      },
      {
        "pos": [
          13,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 1
        },
        "label": "rail_direction=0"
      },
      {
        "pos": [
          13,
          1,
          10
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 0
        },
        "label": "rail_direction=1"
      },
      {
        "pos": [
          13,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 4
        },
        "label": "rail_direction=2"
      },
      {
        "pos": [
          13,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 5
        },
        "label": "rail_direction=3"
      },
      {
        "pos": [
          13,
          1,
          1
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 3
        },
        "label": "rail_direction=4"
      },
      {
        "pos": [
          16,
          1,
          22
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 2
        },
        "label": "rail_direction=5"
      },
      {
        "pos": [
          16,
          1,
          19
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 9
        },
        "label": "rail_direction=6"
      },
      {
        "pos": [
          16,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 6
        },
        "label": "rail_direction=7"
      },
      {
        "pos": [
          16,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 7
        },
        "label": "rail_direction=8"
      },
      {
        "pos": [
          16,
          1,
          10
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 8
        },
        "label": "rail_direction=9"
      },
      {
        "pos": [
          16,
          1,
          7
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "up"
        },
        "label": "minecraft:block_face=up"
      },
      {
        "pos": [
          16,
          1,
          4
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "west"
        },
        "label": "minecraft:block_face=north"
      },
      {
        "pos": [
          16,
          1,
          1
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "east"
        },
        "label": "minecraft:block_face=south"
      },
      {
        "pos": [
          19,
          1,
          22
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "north"
        },
        "label": "minecraft:block_face=east"
      },
      {
        "pos": [
          19,
          1,
          19
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "south"
        },
        "label": "minecraft:block_face=west"
      }
    ]
  },
  "mirror_x": {
    "footprint": [
      24,
      4,
      21
    ],
    "cells": [
      {
        "pos": [
          22,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 1
        },
        "label": "weirdo_direction=0"
      },
      {
        "pos": [
          19,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 0
        },
        "label": "weirdo_direction=1"
      },
      {
        "pos": [
          16,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 2
        },
        "label": "weirdo_direction=2"
      },
      {
        "pos": [
          13,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 3
        },
        "label": "weirdo_direction=3"
      },
      {
        "pos": [
          10,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 1
        },
        "label": "weirdo_direction=0 (upsidedown)"
      },
      {
        "pos": [
          7,
          1,
          1
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 2
        },
        "label": "weirdo_direction=2 (upsidedown)"
      },
      {
        "pos": [
          4,
          1,
          1
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=0"
      },
      {
        "pos": [
          1,
          1,
          1
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=1"
      },
      {
        "pos": [
          22,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=2"
      },
      {
        "pos": [
          19,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=3"
      },
      {
        "pos": [
          16,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=0 (open)"
      },
      {
        "pos": [
          13,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=1 (open)"
      },
      {
        "pos": [
          10,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=2 (open)"
      },
      {
        "pos": [
          7,
          1,
          4
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=3 (open)"
      },
      {
        "pos": [
          4,
          1,
          4
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 0
        },
        "label": "facing_direction=0"
      },
      {
        "pos": [
          1,
          1,
          4
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 1
        },
        "label": "facing_direction=1"
      },
      {
        "pos": [
          22,
          1,
          7
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 2
        },
        "label": "facing_direction=2"
      },
      {
        "pos": [
          19,
          1,
          7
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 3
        },
        "label": "facing_direction=3"
      },
      {
        "pos": [
          16,
          1,
          7
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 5
        },
        "label": "facing_direction=4"
      },
      {
        "pos": [
          13,
          1,
          7
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 4
        },
        "label": "facing_direction=5"
      },
      {
        "pos": [
          10,
          1,
          7
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 0
        },
        "label": "ground_sign_direction=0"
      },
      {
        "pos": [
          7,
          1,
          7
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 14
        },
        "label": "ground_sign_direction=2"
      },
      {
        "pos": [
          4,
          1,
          7
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 12
        },
        "label": "ground_sign_direction=4"
      },
      {
        "pos": [
          1,
          1,
          7
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 10
        },
        "label": "ground_sign_direction=6"
      },
      {
        "pos": [
          22,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 8
        },
        "label": "ground_sign_direction=8"
      },
      {
        "pos": [
          19,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 6
        },
        "label": "ground_sign_direction=10"
      },
      {
        "pos": [
          16,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 4
        },
        "label": "ground_sign_direction=12"
      },
      {
        "pos": [
          13,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 2
        },
        "label": "ground_sign_direction=14"
      },
      {
        "pos": [
          10,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "north"
        },
        "label": "minecraft:cardinal_direction=north"
      },
      {
        "pos": [
          7,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "south"
        },
        "label": "minecraft:cardinal_direction=south"
      },
      {
        "pos": [
          4,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "west"
        },
        "label": "minecraft:cardinal_direction=east"
      },
      {
        "pos": [
          1,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "east"
        },
        "label": "minecraft:cardinal_direction=west"
      },
      {
        "pos": [
          22,
          1,
          13
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "x"
        },
        "label": "pillar_axis=x"
      },
      {
        "pos": [
          19,
          1,
          13
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "y"
        },
        "label": "pillar_axis=y"
      },
      {
        "pos": [
          16,
          1,
          13
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "z"
        },
        "label": "pillar_axis=z"
      },
      {
        "pos": [
          13,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 0
        },
        "label": "rail_direction=0"
      },
      {
        "pos": [
          10,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 1
        },
        "label": "rail_direction=1"
      },
      {
        "pos": [
          7,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 3
        },
        "label": "rail_direction=2"
      },
      {
        "pos": [
          4,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 2
        },
        "label": "rail_direction=3"
      },
      {
        "pos": [
          1,
          1,
          13
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 4
        },
        "label": "rail_direction=4"
      },
      {
        "pos": [
          22,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 5
        },
        "label": "rail_direction=5"
      },
      {
        "pos": [
          19,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 7
        },
        "label": "rail_direction=6"
      },
      {
        "pos": [
          16,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 6
        },
        "label": "rail_direction=7"
      },
      {
        "pos": [
          13,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 9
        },
        "label": "rail_direction=8"
      },
      {
        "pos": [
          10,
          1,
          16
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 8
        },
        "label": "rail_direction=9"
      },
      {
        "pos": [
          7,
          1,
          16
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "up"
        },
        "label": "minecraft:block_face=up"
      },
      {
        "pos": [
          4,
          1,
          16
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "north"
        },
        "label": "minecraft:block_face=north"
      },
      {
        "pos": [
          1,
          1,
          16
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "south"
        },
        "label": "minecraft:block_face=south"
      },
      {
        "pos": [
          22,
          1,
          19
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "west"
        },
        "label": "minecraft:block_face=east"
      },
      {
        "pos": [
          19,
          1,
          19
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "east"
        },
        "label": "minecraft:block_face=west"
      }
    ]
  },
  "mirror_z": {
    "footprint": [
      24,
      4,
      21
    ],
    "cells": [
      {
        "pos": [
          1,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 0
        },
        "label": "weirdo_direction=0"
      },
      {
        "pos": [
          4,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 1
        },
        "label": "weirdo_direction=1"
      },
      {
        "pos": [
          7,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 3
        },
        "label": "weirdo_direction=2"
      },
      {
        "pos": [
          10,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": false,
          "weirdo_direction": 2
        },
        "label": "weirdo_direction=3"
      },
      {
        "pos": [
          13,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 0
        },
        "label": "weirdo_direction=0 (upsidedown)"
      },
      {
        "pos": [
          16,
          1,
          19
        ],
        "block": "minecraft:oak_stairs",
        "state": {
          "upside_down_bit": true,
          "weirdo_direction": 3
        },
        "label": "weirdo_direction=2 (upsidedown)"
      },
      {
        "pos": [
          19,
          1,
          19
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=0"
      },
      {
        "pos": [
          22,
          1,
          19
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=1"
      },
      {
        "pos": [
          1,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=2"
      },
      {
        "pos": [
          4,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": false,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=3"
      },
      {
        "pos": [
          7,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 0
        },
        "label": "direction=0 (open)"
      },
      {
        "pos": [
          10,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 3
        },
        "label": "direction=1 (open)"
      },
      {
        "pos": [
          13,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 2
        },
        "label": "direction=2 (open)"
      },
      {
        "pos": [
          16,
          1,
          16
        ],
        "block": "minecraft:oak_trapdoor",
        "state": {
          "open_bit": true,
          "upside_down_bit": false,
          "direction": 1
        },
        "label": "direction=3 (open)"
      },
      {
        "pos": [
          19,
          1,
          16
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 0
        },
        "label": "facing_direction=0"
      },
      {
        "pos": [
          22,
          1,
          16
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 1
        },
        "label": "facing_direction=1"
      },
      {
        "pos": [
          1,
          1,
          13
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 3
        },
        "label": "facing_direction=2"
      },
      {
        "pos": [
          4,
          1,
          13
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 2
        },
        "label": "facing_direction=3"
      },
      {
        "pos": [
          7,
          1,
          13
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 4
        },
        "label": "facing_direction=4"
      },
      {
        "pos": [
          10,
          1,
          13
        ],
        "block": "minecraft:dropper",
        "state": {
          "triggered_bit": false,
          "facing_direction": 5
        },
        "label": "facing_direction=5"
      },
      {
        "pos": [
          13,
          1,
          13
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 8
        },
        "label": "ground_sign_direction=0"
      },
      {
        "pos": [
          16,
          1,
          13
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 6
        },
        "label": "ground_sign_direction=2"
      },
      {
        "pos": [
          19,
          1,
          13
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 4
        },
        "label": "ground_sign_direction=4"
      },
      {
        "pos": [
          22,
          1,
          13
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 2
        },
        "label": "ground_sign_direction=6"
      },
      {
        "pos": [
          1,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 0
        },
        "label": "ground_sign_direction=8"
      },
      {
        "pos": [
          4,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 14
        },
        "label": "ground_sign_direction=10"
      },
      {
        "pos": [
          7,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 12
        },
        "label": "ground_sign_direction=12"
      },
      {
        "pos": [
          10,
          1,
          10
        ],
        "block": "minecraft:standing_sign",
        "state": {
          "ground_sign_direction": 10
        },
        "label": "ground_sign_direction=14"
      },
      {
        "pos": [
          13,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "south"
        },
        "label": "minecraft:cardinal_direction=north"
      },
      {
        "pos": [
          16,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "north"
        },
        "label": "minecraft:cardinal_direction=south"
      },
      {
        "pos": [
          19,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "east"
        },
        "label": "minecraft:cardinal_direction=east"
      },
      {
        "pos": [
          22,
          1,
          10
        ],
        "block": "minecraft:furnace",
        "state": {
          "minecraft:cardinal_direction": "west"
        },
        "label": "minecraft:cardinal_direction=west"
      },
      {
        "pos": [
          1,
          1,
          7
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "x"
        },
        "label": "pillar_axis=x"
      },
      {
        "pos": [
          4,
          1,
          7
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "y"
        },
        "label": "pillar_axis=y"
      },
      {
        "pos": [
          7,
          1,
          7
        ],
        "block": "minecraft:oak_log",
        "state": {
          "pillar_axis": "z"
        },
        "label": "pillar_axis=z"
      },
      {
        "pos": [
          10,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 0
        },
        "label": "rail_direction=0"
      },
      {
        "pos": [
          13,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 1
        },
        "label": "rail_direction=1"
      },
      {
        "pos": [
          16,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 2
        },
        "label": "rail_direction=2"
      },
      {
        "pos": [
          19,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 3
        },
        "label": "rail_direction=3"
      },
      {
        "pos": [
          22,
          1,
          7
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 5
        },
        "label": "rail_direction=4"
      },
      {
        "pos": [
          1,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 4
        },
        "label": "rail_direction=5"
      },
      {
        "pos": [
          4,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 9
        },
        "label": "rail_direction=6"
      },
      {
        "pos": [
          7,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 8
        },
        "label": "rail_direction=7"
      },
      {
        "pos": [
          10,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 7
        },
        "label": "rail_direction=8"
      },
      {
        "pos": [
          13,
          1,
          4
        ],
        "block": "minecraft:rail",
        "state": {
          "rail_direction": 6
        },
        "label": "rail_direction=9"
      },
      {
        "pos": [
          16,
          1,
          4
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "up"
        },
        "label": "minecraft:block_face=up"
      },
      {
        "pos": [
          19,
          1,
          4
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "south"
        },
        "label": "minecraft:block_face=north"
      },
      {
        "pos": [
          22,
          1,
          4
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "north"
        },
        "label": "minecraft:block_face=south"
      },
      {
        "pos": [
          1,
          1,
          1
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "east"
        },
        "label": "minecraft:block_face=east"
      },
      {
        "pos": [
          4,
          1,
          1
        ],
        "block": "minecraft:stone_button",
        "state": {
          "minecraft:block_face": "west"
        },
        "label": "minecraft:block_face=west"
      }
    ]
  }
}
